- name: Update apt and install required packages
  apt:
    update_cache: yes
#    upgrade: yes
    name:
      - git
      - python3-pip
      - python3-venv
    state: present

- name: Ensure rsync is installed on the target server
  apt:
    name: rsync
    state: present
    update_cache: yes
