- name: Create NGINX configuration for FastAPI
  copy:
    dest: /etc/nginx/sites-available/assistant-backend
    content: |
      server {
          listen 80;
          server_name _;

          location / {
              proxy_pass http://127.0.0.1:8000;
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "upgrade";
              proxy_set_header Host $host;
              proxy_cache_bypass $http_upgrade;
          }
      }
    owner: root
    group: root
    mode: "0644"

- name: Enable NGINX site configuration
  file:
    src: /etc/nginx/sites-available/assistant-backend
    dest: /etc/nginx/sites-enabled/assistant-backend
    state: link

- name: Remove default NGINX configuration
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Test NGINX configuration
  command: nginx -t

- name: Restart NGINX
  service:
    name: nginx
    state: restarted
